In [3]:
import numpy as np

Suma de matrices

In [7]:
# Solo se puede hacer suma de matrices simpre cuando sea del mismo orden
# Como por ejemplo(3x3) x (3x3)
# Ejercicio n°1
A = np.array([[-3, 0], [2, 5], [8, -7]])
B = np.array([[7, -5], [4, -2], [1, -4]])

In [8]:
# Sumando las matrices 
suma_matriz = np.add(A,B)
suma_matriz

array([[  4,  -5],
       [  6,   3],
       [  9, -11]])

In [29]:
# Ejercicios número 2: Econtrar la sumas de 3 matrices
A = np.array([[-5, 10, 0], [2, -14, 9], [-6, 3, 8]])
B = np.array([[-8, 3, 4], [-9, 7, -5], [15, -3, 0]])
C = np.array([[5, 0, 2], [-4, 6, 10], [0, -5, 1]])

# Hallar la suma:
# A + b =
# A + C =
# B + C =
# A + B + C =

In [19]:
# Hallando A  + B
suma_a_b = np.add(A, B)
suma_a_b

array([[-13,  13,   4],
       [ -7,  -7,   4],
       [  9,   0,   8]])

In [12]:
# Hallando A  + C
suma_a_c = np.add(A, C)
suma_a_c

array([[ 0, 10,  2],
       [-2, -8, 19],
       [-6, -2,  9]])

In [13]:
# Hallando B + C
suma_b_c = np.add(B, C)
suma_b_c

array([[ -3,   3,   6],
       [-13,  13,   5],
       [ 15,  -8,   1]])

In [35]:
# Hallando A + B + C
# Usaremos el resultado de la matriz A + B y sumamos con la matriz C
C



array([[ 5,  0,  2],
       [-4,  6, 10],
       [ 0, -5,  1]])

In [36]:
suma_a_b_c = np.add(suma_a_b, C)
suma_a_b_c

array([[ -8,  13,   6],
       [-11,  -1,  14],
       [  9,  -5,   9]])

RESTA DE MATRICES

In [50]:
import numpy as np
# La resta solo se puede realizar si es del mismo orden
# Ojo, no es lo mismo C-D que D-C
# C-D = ?

C = np.array([[0,-8, 9], [14,-3, 5],[20, 0, -15]])
D = np.array([[4, -2, 6], [7, 5, 12], [0,-2, -8]])

In [51]:
resta = np.subtract(C, D)
resta

array([[-4, -6,  3],
       [ 7, -8, -7],
       [20,  2, -7]])

In [52]:
# D-C = ?
resta2 = np.subtract(D, C)
resta2

array([[  4,   6,  -3],
       [ -7,   8,   7],
       [-20,  -2,   7]])